require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("lsp")

require('plugins')
require('settings')
require('autopairs')
require('barbar')
require('comments')
require('completion')
require('telescope')
require('treesitter')
